### ISSUE TITLE
Set/GetThreadContext

### ISSUE THREAD

**Issue by gordon0001** [biocomp/hw_break#3]
Please read the remarks about Set/GetThreadContext
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreadcontext
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreadcontext

You have to Suspend the thread before using the above functions, and resume them after.

> You cannot get a valid context for a running thread. Use the [SuspendThread](https://learn.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-suspendthread) function to suspend the thread before calling GetThreadContext.

> Do not try to set the context for a running thread; the results are unpredictable. Use the [SuspendThread](https://learn.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-suspendthread) function to suspend the thread before calling SetThreadContext.

> If you call GetThreadContext for the current thread, the function returns successfully; however, the context returned is not valid.

The code in test.cpp is complete trash. No one would use it like that.
Better use try catch/except for your code if you want exception handling.
For use in an debugger or for hooking purposes your library is not suitable.

In general not really a clean implementation for a library and it is incomplete. No adding and handling of exception handlers. If breakpoint is hit you should check which debug register was hit, Dr6 contains this info.

**Comment by biocomp** [comment]
Sorry, my reply was a little delayed. I know what the docs say about using a separate thread, but it was not possible to do in my scenario (too slow), and it turned out that just doing it on the same thread worked.

As for implementation being a "complete trash", I should mention that I used it exactly like it is. And it worked for me, but I can admit that I was not under debugger, I needed a crash to be generated.

I agree that the library is not perfect. If you have more specific suggestions, PRs are welcome.
